config/routes.rb
Rails.application.routes.draw do
  #get 'contacts/index'
 # resources :contacts
  #devise_for :users
  
  #	devise_scope :user do
  #		authenticated :user do
  #			root 'contacts#new', as: :authenticated_root
  #		end
  #		unauthenticated do
  #			root 'devise/sessions#new', as: :unauthenticated_root
  #		end
  #	end

  #get 'home/index'
  

  devise_for :users, controllers: { registrations: "registrations"}
 # resources :phones
  resources :contacts
  get :send_mail, to: 'contacts#send_mail', as: :send_mail
  root 'home#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user
	has_many :phone, dependent: :destroy 
    has_many :email, dependent: :destroy
    accepts_nested_attributes_for :phone,allow_destroy: true
    accepts_nested_attributes_for :email,allow_destroy: true
    validates :firstname, :lastname, :address, :presence=> true, :length => { :minimum => 3, :maximum => 20 } 
end

app/models/email.rb
class Email < ApplicationRecord
	belongs_to :contact, optional: true
	validates :email, :presence => true, format: { with: URI::MailTo::EMAIL_REGEXP } 
end

app/models/phone.rb
class Phone < ApplicationRecord
	belongs_to :contact, optional: true
	#validates_format_of :phone, :with =>  /\d[0-9]\)*\z/
	validates :phone,:presence => true,	
					:length => { :minimum => 7, :maximum => 10 }, 
					format: { :with =>  /\d[0-9]\)*\z/ }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contact
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :authenticate_user!
  before_action :find_contact, only: [:send_mail, :edit, :update, :destroy, :show]
  def index
  	  search = (params[:search]).to_s.downcase
      @contacts = (current_user.contact).where("lower(firstname) LIKE ? 
      OR lower(lastname) LIKE ? OR lower(firstname || ' ' || lastname) LIKE ? OR lower(address) LIKE ?","%#{search}%","%#{search}%","%#{search}%","%#{search}%" ).paginate(:page => params[:page], :per_page => 7)
  end

  def new
  	@contact = Contact.new
  	@contact.user = current_user
    @contact.phone.build
    @contact.email.build
  	
  end
  def create
  	@contact = Contact.new(contact_params)
    @contact.user = current_user
  	if @contact.save
     	flash[:success] = "Successfully created new contact"
       #ContactMailer.greeting_email(@contact).deliver_now
  		redirect_to contact_path(@contact)
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def show
  	
  end

  def send_mail
    ContactMailer.greeting_email(@contact).deliver_now
    flash[:success] = "Mail sent successfully"
    redirect_to contacts_path
  end

  def destroy
    @contact.destroy
  	flash[:success] = "Successfully deleted contact"
    redirect_to contacts_path
  end
  def update
  	@contact.user = current_user
  	if @contact.update(contact_params)
  		flash[:success] = "Successfully updated contact"
  		redirect_to contact_path
  	else
  		render 'edit'
  	end
  end
 

  def find_contact
    @contact = Contact.find(params[:id])

  end
   private

  def contact_params
    params.require(:contact).permit(:firstname, :lastname, :address,phone_attributes: Phone.attribute_names.map(&:to_sym).push(:_destroy),email_attributes: Email.attribute_names.map(&:to_sym).push(:_destroy))
  end

end

app/controllers/home_controller.rb
  class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to contacts_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:email,:password,:password_confirmation)
    end 
    
    def account_update_params
        params.require(:user).permit(:email,:password,:password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def link_to_add_row(name, f, association, **args)
        new_object = f.object.send(association).klass.new
        id = new_object.object_id
        fields = f.fields_for(association, new_object, child_index: id) do |builder|
          render(association.to_s.singularize, f: builder)
        end
        link_to(name, '#', class: "add_fields " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
    end

     def link_to_add_row1(name, f, association, **args)
        new_object = f.object.send(association).klass.new
        id = new_object.object_id
        fields = f.fields_for(association, new_object, child_index: id) do |ad|
          render(association.to_s.singularize, f: ad)
        end
        link_to(name, '#', class: "add_fields1 " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
    end

    def is_active(action)       
      params[:action] == action ? "active" : nil        
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/contacts/_email.html.erb
<!-- <div class="form-group"> -->
    <div class="row">
    <div class="col-md-2">
	   	<%= f.select :label, ['Work', 'Personal', 'Others'], style:"width: 100%" %>
	</div>

	<div class="col-md-6">
    <%= f.text_field :email,class: "form-control", style:"margin-bottom: 15px" %>
    </div>
    <%= f.hidden_field :_destroy %>
    <% if $counta != 1%>
        <%= link_to 'Delete', '#', class: 'remove_record2',  id: 'deleteradd'  %>
    <% end %>  
    </div>  
<!-- </div>   -->

app/views/contacts/_form.html.erb
<%= form_for @contact, html: { multipart: true } do |f| %>          
    <div class="panel-body">     
      <% if @contact.errors.any? %>
              <ul>
                <% @contact.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul> 

      <% end %>


      <div class="form-group">
        <%= f.label :firstname %> 
        <%= f.text_field :firstname, class: "form-control", style:"width : 66%" %>
      </div>

      <div class="form-group">
        <%= f.label :lastname, class: "control-label" %>  
         <%= f.text_field :lastname, class: "form-control" , style:"width : 66%" %> 
      </div>

      <div class="form-group">
        <div class="fields">
                <%$counta = 1%>
                <%= f.label :phone, class: "control-label", id: "formlabel" %> 
                <%= f.fields_for :phone do |ad| %>
                  <div class="form-group">
                    <%= render 'phone', f: ad %>
                  </div>
                  <% $counta = $counta + 1%>
                <% end %>
              </div> 
         <%= link_to_add_row('Add Phone',f,:phone , class: "btn btn-primary pull-centre")%>
      </div>

       <div class="form-group">
        <div class="fields2">
                <%$counta = 1%>
                <%= f.label :email, class: "control-label", id: "formlabel" %> 
                <%= f.fields_for :email do |ad| %>
                  <div class="form-group">
                    <%= render 'email', f: ad %>
                  </div>
                  <% $counta = $counta + 1%>
                <% end %>
              </div> 
               <%= link_to_add_row1('Add Email',f,:email , class: "btn btn-primary pull-centre")%>
        </div>

      <div class="form-group">
        <%= f.label :address %> 
        <%= f.text_field :address, class: "form-control",style:"width : 66%" %>
      </div>     
</div>
<div class="panel-footer">

    <div class="form-inline">
        <button type="submit" class="btn btn-primary">Save</button>
        <%= link_to "Cancel", contacts_path, class: "btn btn-danger" %>           
    </div>
</div>
<% end %>

app/views/contacts/_phone.html.erb
 <div class="row">
    <div class="col-md-2">
	   	<%= f.select :label, ['Work', 'Personal', 'Others'] %>
	</div>

	<div class="col-xs-6">
    <%= f.text_field :phone, class: "form-control", style:"margin-bottom: 15px" %>
    </div>
    <%= f.hidden_field :_destroy %>
    <% if $counta != 1%>
        <%= link_to 'Delete', '#', class: 'remove_record',  id: 'deleter'  %>
    <% end %>  
    </div>  

app/views/contacts/edit.html.erb
<div class="panel panel-default custom-panel-position" style="width: 700px;">
<div class="panel-heading">
	<h3><strong>Edit Contact</strong></h3>
</div>
<%= render 'form' %>
</div>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-md-8"> <h1><span class="glyphicon glyphicon-user"></span> <strong>Contacts</strong> </h1></div>
    <div class="col-md-4" style="padding-top: 20px; padding-left: 130px">
      <button type="button" class="btn btn-primary"><%= @contacts.count %> Contact(s)</button>
      <%= link_to new_contact_path ,  class: "btn btn-primary" do %>
      <i class="glyphicon glyphicon-plus"></i> 
      Add Contact
      <% end %>
    </div>
  </div><br>

  <% if user_signed_in? %>
    <div class="row">
      <div class="text-left">
      <%= form_tag contacts_path, :method => 'get', class: 'input-group'  do %>
      <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search for contacts...' %>
      <span class="input-group-btn">
      <%= submit_tag "search", class: "btn btn-default" %>
      </span>
      <% end %>
      </div>
    <div>
  <% end %>
</div>


<div class=" col-md-12 panel panel-default">
  <table class="table">
    <!--Display result not found message when search result not found-->
    <% if params[:search].present? %>
      <% if !@contacts.present? %>
        No result found
      <% end %>
    <% end %>
        
      <!--Display all the contacts-->
    <% @contacts.order(:firstname).each do |contact| %>
      <tr>
          <td class="middle">
          <h1><%= contact.firstname.capitalize %> <%= contact.lastname.capitalize %></h1>
          </td>
          
          <td width="10" class="middle">
          <%= link_to "Show",contact, class: "btn btn-info", title: "View" %>
          </td>
          
          <td width="90" class="middle">
            <div class="btn btn-default">
            <%= link_to "Send Mail", class: "btn btn-primary pull-centre", :controller => "contacts", :action => "send_mail", :id => contact.id %>
            </div>
          </td>

          <td width="20" class="middle">        
            <%= link_to "Delete", contact_path(contact), :method => :delete, class: "btn btn-danger pull-centre", title: "Delete",data: { confirm: "Are you sure ?" }  %>
          </td>
      </tr>
    <% end %>
  </table>

  <div class="text-right">
   <b> <%= will_paginate @contacts %></b>
  </div>            
</div>

app/views/contacts/new.html.erb
<div class="panel panel-default custom-panel-position" style= "width:700px;">
  <div class="panel-heading text-center">
    <h3><strong><span class="glyphicon glyphicon-plus"></span> Add Contact</strong></h3>
  </div> 

<%= render 'form' %>
</div>

app/views/contacts/show.html.erb
<div class="panel panel-default custom-panel-position" style="width: 700px;">
    <div class="panel-heading">
     <h3><strong><%= @contact.firstname.capitalize %>  <%= @contact.lastname.capitalize %> </strong> </h3>
    </div> 
        
  <div class="panel-body">
        <div class="form-group">
        <label class="control-label">Phone</label> 
        
            <% @contact.phone.each do |b| %>
                  <div class="adderfield">
                      <label class="control-label"> <%= b.label %> : </label>            
                      <%= b.phone %>        
                  </div> 
            <% end %>
       
    </div>
    <hr>

    <div class="form-group">
        <label class="control-label">Email</label> 
        
            <% @contact.email.each do |b| %>
                  <div class="adderfield">
                      <label class="control-label"> <%= b.label %> : </label>            
                      <%= b.email %>        
                  </div> 
               
            <% end %>
        
    </div>
    <hr>

    <div class="form-group">
        <label class="control-label">Address</label> 
        <div><%= @contact.address %></div>
    </div>
  </div>

  <div class="panel-footer">
    <div class="form-group">          
        <%= link_to "Edit", edit_contact_path, class: "btn btn-primary" %>
        <%= link_to "Delete", contact_path,:method => :delete, class: "btn btn-danger", title: "Delete", data: { confirm: "Are you sure ?" }%> 
         <%= link_to "Back", contacts_path, class: "btn btn-primary" %>            
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts Manager</title>
   <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>

  </head>

  <body>
  <nav class="navbar navbar-fixed-top" >
      <div class="container">
        <div class="navbar-header">
         
          <%= link_to "Contacts Manager", root_path, class: "navbar-brand text-uppercase" %>          
        </div>
        <!-- /.navbar-header -->

      
        <% if user_signed_in? %>
          <div class="collapse navbar-collapse" id="navbar-collapse">
          
            <div class="navbar-nav navbar-right nav btn">

            <%= link_to edit_user_registration_path, class: "btn btn-default" do %>
            <i class="fas fa-user-edit"></i> 
            Edit Profile
          <% end %>  
            
             <%= link_to destroy_user_session_path, :method => 'delete' , class: "btn btn-default" do%>
            <i class="glyphicon glyphicon-log-out"></i> 
            Logout
          <% end %>
            
            
          </div>
        <% else %>
          <div class="collapse navbar-collapse" id="navbar-collapse">
          
            <div class="navbar-nav navbar-right nav btn">

            <%= link_to new_session_path(resource_name),class: "btn btn-default" do%>
            <i class="fas fa-sign-in-alt"></i>&nbsp;Login
            <% end %>
            
            <%= link_to  new_registration_path(resource_name) , class: "btn btn-default" do%>
            <span class="nav-link"><i class="fas fa-user-plus"></i>&nbsp;Register</span>
            <% end %>
            
            
          </div>

        <% end %>
      </div>
    </nav>
    <div class="container">

          <!--Flash Messages-->
          <% flash.each do |type, message| %>
            
              <%= content_tag :div, class: "alert alert-#{type} alert-dismissible", role: "alert" do %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <%= message %>
              <% end %> 
             
          <% end %> 

          <%= yield %>
          <div class="footer text-center">
          <p> &copy; Contacts Manager <%= Date.today.year %> All Rights Reserved</p>    
          </div>
        </div>
      </div>
    </div>
  </body>
</html>